### ISSUE TITLE
No distributions at all found for paragram

### ISSUE THREAD

**Issue by hayd** [timbertson/paragram#5]
There seems to be an issue on pip, there's no files uploaded! https://pypi.python.org/pypi/paragram

```
 % pip install paragram
Downloading/unpacking paragram
  Could not find any downloads that satisfy the requirement paragram
  Some externally hosted files were ignored (use --allow-external paragram to allow).
Cleaning up...
No distributions at all found for paragram
Storing debug log for failure in /Users/andy/Library/Logs/pip.log
```

**Comment by hayd** [comment]
This has the side-effect of not being able to install autonose.

**Comment by gfxmonk** [comment]
Ok, I've uploaded an archive. Fair warning though: paragram and autonose haven't been touched for years (in which tie pypi changed its policy on third-party archives), so I've no idea if autonose in particular even works any more :/
